<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Nicky Nie" />


<title>PM566 Final Project</title>

<script src="site_libs/jquery-1.12.4/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="site_libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="site_libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="site_libs/leaflet-1.3.1/leaflet.js"></script>
<link href="site_libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="site_libs/proj4-2.6.2/proj4.min.js"></script>
<script src="site_libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="site_libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="site_libs/leaflet-binding-2.0.4.1/leaflet.js"></script>
<script src="site_libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="site_libs/leaflet-providers-plugin-2.0.4.1/leaflet-providers-plugin.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">PM566 Final Project</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Final Project</a>
</li>
<li>
  <a href="12-lab.html">Lab 12</a>
</li>
<li>
  <a href="https://covidtracking.com/race">Data</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/USCbiostats/PM566">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li class="dropdown-header">Download Report</li>
<li>
  <a href="https://github.com/Nicky-Nie/PM566_final">Respository</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">PM566 Final Project</h1>
<h4 class="author">Nicky Nie</h4>

</div>


<p><br></p>
<p>This is my PM566 Final Project website. I will showcase major finding in report here. Full report can be downloaded from the website.</p>
<p><br></p>
<style type="text/css">
.code-r { /* Code block */
  font-size: 15px;
}

.code-r-small { /* Code block */
  font-size: 10px;
}
</style>
<p><br></p>
<div id="introduction-of-dataset" class="section level1">
<h1>Introduction of dataset</h1>
<p>This dataset is a collaboration between the COVID Tracking Project and the Boston University Center for Antiracist Research, which shows the counts of cases/deaths of COVID-19 catrgotized by races for each state in United States. The data was collected from April 12, 2020 to March 07, 2021.</p>
<div id="main-question-is-death-from-covid-19-associated-with-races" class="section level2">
<h2>Main Question: Is death from COVID-19 associated with races?</h2>
</div>
</div>
<div id="method" class="section level1">
<h1>Method</h1>
<div id="download-data" class="section level3">
<h3>Download data</h3>
<p>I download data in csv form from The COVID Tracking Project <a href="https://covidtracking.com/race" class="uri">https://covidtracking.com/race</a> And dataset of latitude and longitude of each state is download from kaggle <a href="https://www.kaggle.com/washimahmed/usa-latlong-for-state-abbreviations" class="uri">https://www.kaggle.com/washimahmed/usa-latlong-for-state-abbreviations</a></p>
<pre class="r code-r"><code>race &lt;- fread(&quot;CRDT.csv&quot;)
state_map &lt;- fread(&quot;statelatlong.csv&quot;)</code></pre>
</div>
<div id="preprocessing-data" class="section level3">
<h3>Preprocessing data</h3>
<pre class="r code-r"><code>tab &lt;- race[, .(
Total_objects = nrow(race),
NA_total = sum(is.na(race$Cases_Total)),
NA_white = sum(is.na(race$Cases_White)),
NA_black = sum(is.na(race$Cases_Black)),
NA_latinx = sum(is.na(race$Cases_Latinx)),
NA_asian = sum(is.na(race$Cases_Asian)),
NA_AIAN = sum(is.na(race$Cases_AIAN)),
NA_NHPI = sum(is.na(race$Cases_NHPI)),
NA_multi = sum(is.na(race$Cases_Multiracial))
)]
knitr::kable(tab)</code></pre>
<table style="width:100%;">
<colgroup>
<col width="16%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="11%" />
<col width="10%" />
<col width="9%" />
<col width="9%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Total_objects</th>
<th align="right">NA_total</th>
<th align="right">NA_white</th>
<th align="right">NA_black</th>
<th align="right">NA_latinx</th>
<th align="right">NA_asian</th>
<th align="right">NA_AIAN</th>
<th align="right">NA_NHPI</th>
<th align="right">NA_multi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">5320</td>
<td align="right">232</td>
<td align="right">652</td>
<td align="right">733</td>
<td align="right">3248</td>
<td align="right">950</td>
<td align="right">2057</td>
<td align="right">3139</td>
<td align="right">3795</td>
</tr>
</tbody>
</table>
<p>Based on this table, I decided to take a close look at data of Total, White, Black and Asian since races like Latinx, AIAN, NHPI and multiracial have almost half of missing data, which is not suitable for further analysis. And for the three races categories left, I dropped all the NAs for further analysis.</p>
<p>I firstly created two new datasets, one is based on state(race_state) and another(race_country) is based on country. Then I calculated death rates based on races of each dataset. I also created a dataset of CA to see if pattern in CA is similar to the pattern of the whole country. And since the number of cases and deaths are cumulative, I chose the latest data(2021.03.07) and created a new dataset called “latest” to find the race with highest death rate in each state.</p>
<pre class="r code-r"><code># pick up interested variables
race_state &lt;- unique(race[,.(Date,State,Cases_Total,Cases_White,Cases_Black,Cases_Asian,Deaths_Total,Deaths_White,Deaths_Black,Deaths_Asian)])
# since date here shows to be integer, I changed them into str
race_state$Date = as.Date(as.character(race$Date),&quot;%Y%m%d&quot;)

# drop NAs
race_state &lt;- race_state[!is.na(Cases_Total) &amp; !is.na(Cases_White) &amp; !is.na(Cases_Black) &amp; !is.na(Cases_Asian) &amp; !is.na(Deaths_Total) &amp; !is.na(Deaths_White) &amp; !is.na(Deaths_Black) &amp; !is.na(Deaths_Asian)]
sum(is.na(race_state))</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r code-r"><code># Calculate total cases of different races based on date
race_country &lt;- race_state[,.(
  Case_total  = sum(Cases_Total),
  Case_white  = sum(Cases_White),
  Case_black  = sum(Cases_Black),
  Case_asian  = sum(Cases_Asian),
  Death_total = sum(Deaths_Total),
  Death_white = sum(Deaths_White),
  Death_black = sum(Deaths_Black),
  Death_asian = sum(Deaths_Asian)
), by = Date]

# Calculate death rate
race_state  [, DR_total := Deaths_Total/Cases_Total]
race_state  [, DR_white := Deaths_White/Cases_White]
race_state  [, DR_black := Deaths_Black/Cases_Black]
race_state  [, DR_asian := Deaths_Asian/Cases_Asian]
race_country[, DR_total := Death_total/Case_total]
race_country[, DR_white := Death_white/Case_white]
race_country[, DR_black := Death_black/Case_black]
race_country[, DR_asian := Death_asian/Case_asian]

# Stick to CA data
CA &lt;- filter(race_state, State == &quot;CA&quot;)

# Race with highest DR in each state.
latest &lt;- filter(race_state, Date == &quot;2021-03-07&quot;)
latest &lt;- latest[, highest_DR := 
         fifelse(DR_white == max(DR_white,DR_black,DR_asian),&quot;White&quot;,
          fifelse(DR_black == max(DR_white,DR_black,DR_asian),&quot;Black&quot;,&quot;Asian&quot;
          )), by = State]</code></pre>
</div>
</div>
<div id="preliminary-results" class="section level1">
<h1>Preliminary Results</h1>
<div id="covid-19-death-rate-of-different-races-in-united-states" class="section level2">
<h2>COVID-19 Death rate of different races in United States</h2>
<pre class="r code-r"><code>ggplot(data = race_country) + 
  geom_smooth(mapping = aes(x = Date, y = DR_white, color = &quot;DR_white&quot;))+
  geom_smooth(mapping = aes(x = Date, y = DR_black, color = &quot;DR_black&quot;))+
  geom_smooth(mapping = aes(x = Date, y = DR_asian, color = &quot;DR_asian&quot;))+
  geom_smooth(mapping = aes(x = Date, y = DR_total,color = &quot;DR_total&quot;))+
  labs(x = &quot;Month&quot;, y = &quot;Death Rate&quot;)+
  labs(title = &quot;COVID-19 Death rate of different races in United States&quot;)+
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=1))+
  scale_x_date(date_breaks = &quot;months&quot; , date_labels = &quot;%b-%y&quot;)</code></pre>
<p><img src="index_files/figure-html/country-1.png" width="700px" style="display: block; margin: auto;" /></p>
<p>From this graph, we can see that the trend of all DR is gradually decreasing, the total death rate is always the lowest one since there are a lot of cases of other or unknown races which largely increase the denominator. And although death rate of white is higher than the other two races initially, they approach to the same level finally with a little bit of difference.</p>
</div>
<div id="covid-19-death-rate-of-different-races-in-california" class="section level2">
<h2>COVID-19 Death rate of different races in California</h2>
<pre class="r code-r"><code>ggplot(data = CA) + 
  geom_smooth(mapping = aes(x = Date, y = DR_white, color = &quot;DR_white&quot;))+
  geom_smooth(mapping = aes(x = Date, y = DR_black, color = &quot;DR_black&quot;))+
  geom_smooth(mapping = aes(x = Date, y = DR_asian, color = &quot;DR_asian&quot;))+
  geom_smooth(mapping = aes(x = Date, y = DR_total,color = &quot;DR_total&quot;))+
  labs(x = &quot;Month&quot;, y = &quot;Death Rate&quot;)+
  labs(title = &quot;COVID-19 Death rate of different races in California&quot;)+
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=1))+
  scale_x_date(date_breaks = &quot;months&quot; , date_labels = &quot;%b-%y&quot;)</code></pre>
<p><img src="index_files/figure-html/CA-1.png" width="700px" style="display: block; margin: auto;" /></p>
<p>The general trend is similar to that of country but it seems that four lines go up slightly at last. But we can still see a trend of DR of three races approaching to the same level at the final stage of the data.</p>
</div>
<div id="death-rate-in-each-state" class="section level2">
<h2>Death rate in each state</h2>
<pre class="r code-r"><code>tab &lt;- latest[, .(
  State = State,
  DR_total = DR_total,
  DR_white = DR_white,
  DR_black = DR_black,
  DR_asian = DR_asian
)]

knitr::kable(tab)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">State</th>
<th align="right">DR_total</th>
<th align="right">DR_white</th>
<th align="right">DR_black</th>
<th align="right">DR_asian</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">AK</td>
<td align="right">0.0051406</td>
<td align="right">0.0069399</td>
<td align="right">0.0060040</td>
<td align="right">0.0118512</td>
</tr>
<tr class="even">
<td align="left">AL</td>
<td align="right">0.0203033</td>
<td align="right">0.0294985</td>
<td align="right">0.0268511</td>
<td align="right">0.0105587</td>
</tr>
<tr class="odd">
<td align="left">AR</td>
<td align="right">0.0163753</td>
<td align="right">0.0200919</td>
<td align="right">0.0154203</td>
<td align="right">0.0123584</td>
</tr>
<tr class="even">
<td align="left">AZ</td>
<td align="right">0.0197567</td>
<td align="right">0.0261499</td>
<td align="right">0.0167992</td>
<td align="right">0.0184548</td>
</tr>
<tr class="odd">
<td align="left">CA</td>
<td align="right">0.0154578</td>
<td align="right">0.0303423</td>
<td align="right">0.0294305</td>
<td align="right">0.0327237</td>
</tr>
<tr class="even">
<td align="left">CO</td>
<td align="right">0.0137369</td>
<td align="right">0.0212970</td>
<td align="right">0.0151143</td>
<td align="right">0.0179519</td>
</tr>
<tr class="odd">
<td align="left">CT</td>
<td align="right">0.0270003</td>
<td align="right">0.0633329</td>
<td align="right">0.0461045</td>
<td align="right">0.0274925</td>
</tr>
<tr class="even">
<td align="left">DC</td>
<td align="right">0.0248678</td>
<td align="right">0.0098058</td>
<td align="right">0.0383356</td>
<td align="right">0.0153173</td>
</tr>
<tr class="odd">
<td align="left">DE</td>
<td align="right">0.0166716</td>
<td align="right">0.0242453</td>
<td align="right">0.0166431</td>
<td align="right">0.0059718</td>
</tr>
<tr class="even">
<td align="left">GA</td>
<td align="right">0.0174951</td>
<td align="right">0.0280037</td>
<td align="right">0.0244460</td>
<td align="right">0.0166592</td>
</tr>
<tr class="odd">
<td align="left">HI</td>
<td align="right">0.0159550</td>
<td align="right">0.0109709</td>
<td align="right">0.0068966</td>
<td align="right">0.0402109</td>
</tr>
<tr class="even">
<td align="left">IA</td>
<td align="right">0.0163629</td>
<td align="right">0.0257178</td>
<td align="right">0.0131501</td>
<td align="right">0.0179570</td>
</tr>
<tr class="odd">
<td align="left">ID</td>
<td align="right">0.0108656</td>
<td align="right">0.0176252</td>
<td align="right">0.0089286</td>
<td align="right">0.0139459</td>
</tr>
<tr class="even">
<td align="left">IL</td>
<td align="right">0.0192050</td>
<td align="right">0.0259433</td>
<td align="right">0.0331343</td>
<td align="right">0.0272217</td>
</tr>
<tr class="odd">
<td align="left">IN</td>
<td align="right">0.0190885</td>
<td align="right">0.0201121</td>
<td align="right">0.0211149</td>
<td align="right">0.0077890</td>
</tr>
<tr class="even">
<td align="left">KS</td>
<td align="right">0.0162644</td>
<td align="right">0.0177400</td>
<td align="right">0.0163992</td>
<td align="right">0.0115837</td>
</tr>
<tr class="odd">
<td align="left">KY</td>
<td align="right">0.0117334</td>
<td align="right">0.0138986</td>
<td align="right">0.0138005</td>
<td align="right">0.0062500</td>
</tr>
<tr class="even">
<td align="left">LA</td>
<td align="right">0.0224720</td>
<td align="right">0.0265559</td>
<td align="right">0.0272827</td>
<td align="right">0.0044953</td>
</tr>
<tr class="odd">
<td align="left">MA</td>
<td align="right">0.0277616</td>
<td align="right">0.0547782</td>
<td align="right">0.0302473</td>
<td align="right">0.0258121</td>
</tr>
<tr class="even">
<td align="left">MD</td>
<td align="right">0.0205386</td>
<td align="right">0.0302754</td>
<td align="right">0.0244214</td>
<td align="right">0.0312394</td>
</tr>
<tr class="odd">
<td align="left">ME</td>
<td align="right">0.0154169</td>
<td align="right">0.0165973</td>
<td align="right">0.0044405</td>
<td align="right">0.0059761</td>
</tr>
<tr class="even">
<td align="left">MI</td>
<td align="right">0.0253905</td>
<td align="right">0.0296323</td>
<td align="right">0.0488960</td>
<td align="right">0.0172747</td>
</tr>
<tr class="odd">
<td align="left">MN</td>
<td align="right">0.0133670</td>
<td align="right">0.0165998</td>
<td align="right">0.0081703</td>
<td align="right">0.0120633</td>
</tr>
<tr class="even">
<td align="left">MO</td>
<td align="right">0.0169793</td>
<td align="right">0.0204635</td>
<td align="right">0.0252862</td>
<td align="right">0.0155200</td>
</tr>
<tr class="odd">
<td align="left">MS</td>
<td align="right">0.0228778</td>
<td align="right">0.0260481</td>
<td align="right">0.0272974</td>
<td align="right">0.0127208</td>
</tr>
<tr class="even">
<td align="left">MT</td>
<td align="right">0.0136849</td>
<td align="right">0.0134534</td>
<td align="right">0.0021739</td>
<td align="right">0.0029240</td>
</tr>
<tr class="odd">
<td align="left">NC</td>
<td align="right">0.0131877</td>
<td align="right">0.0161873</td>
<td align="right">0.0181097</td>
<td align="right">0.0088106</td>
</tr>
<tr class="even">
<td align="left">NE</td>
<td align="right">0.0103716</td>
<td align="right">0.0130129</td>
<td align="right">0.0113348</td>
<td align="right">0.0106800</td>
</tr>
<tr class="odd">
<td align="left">NH</td>
<td align="right">0.0154044</td>
<td align="right">0.0281319</td>
<td align="right">0.0126829</td>
<td align="right">0.0115830</td>
</tr>
<tr class="even">
<td align="left">NJ</td>
<td align="right">0.0290103</td>
<td align="right">0.0481572</td>
<td align="right">0.0535786</td>
<td align="right">0.0387883</td>
</tr>
<tr class="odd">
<td align="left">NM</td>
<td align="right">0.0203721</td>
<td align="right">0.0339408</td>
<td align="right">0.0207627</td>
<td align="right">0.0159953</td>
</tr>
<tr class="even">
<td align="left">NV</td>
<td align="right">0.0170060</td>
<td align="right">0.0251505</td>
<td align="right">0.0207908</td>
<td align="right">0.0244575</td>
</tr>
<tr class="odd">
<td align="left">OH</td>
<td align="right">0.0180445</td>
<td align="right">0.0259273</td>
<td align="right">0.0211917</td>
<td align="right">0.0102879</td>
</tr>
<tr class="even">
<td align="left">OK</td>
<td align="right">0.0105688</td>
<td align="right">0.0133303</td>
<td align="right">0.0117220</td>
<td align="right">0.0072593</td>
</tr>
<tr class="odd">
<td align="left">OR</td>
<td align="right">0.0145977</td>
<td align="right">0.0200269</td>
<td align="right">0.0121340</td>
<td align="right">0.0119588</td>
</tr>
<tr class="even">
<td align="left">PA</td>
<td align="right">0.0256672</td>
<td align="right">0.0400241</td>
<td align="right">0.0348485</td>
<td align="right">0.0234298</td>
</tr>
<tr class="odd">
<td align="left">RI</td>
<td align="right">0.0198328</td>
<td align="right">0.0305781</td>
<td align="right">0.0133676</td>
<td align="right">0.0157985</td>
</tr>
<tr class="even">
<td align="left">SC</td>
<td align="right">0.0166469</td>
<td align="right">0.0198065</td>
<td align="right">0.0224426</td>
<td align="right">0.0104287</td>
</tr>
<tr class="odd">
<td align="left">SD</td>
<td align="right">0.0167270</td>
<td align="right">0.0176819</td>
<td align="right">0.0027789</td>
<td align="right">0.0108992</td>
</tr>
<tr class="even">
<td align="left">TN</td>
<td align="right">0.0147380</td>
<td align="right">0.0178243</td>
<td align="right">0.0195069</td>
<td align="right">0.0096584</td>
</tr>
<tr class="odd">
<td align="left">TX</td>
<td align="right">0.0165441</td>
<td align="right">0.7144365</td>
<td align="right">0.3355429</td>
<td align="right">0.9624866</td>
</tr>
<tr class="even">
<td align="left">UT</td>
<td align="right">0.0052714</td>
<td align="right">0.0055744</td>
<td align="right">0.0035993</td>
<td align="right">0.0083017</td>
</tr>
<tr class="odd">
<td align="left">VA</td>
<td align="right">0.0163838</td>
<td align="right">0.0255112</td>
<td align="right">0.0228102</td>
<td align="right">0.0168635</td>
</tr>
<tr class="even">
<td align="left">VT</td>
<td align="right">0.0129329</td>
<td align="right">0.0145269</td>
<td align="right">0.0032626</td>
<td align="right">0.0067024</td>
</tr>
<tr class="odd">
<td align="left">WA</td>
<td align="right">0.0146314</td>
<td align="right">0.0369776</td>
<td align="right">0.0147274</td>
<td align="right">0.0305788</td>
</tr>
<tr class="even">
<td align="left">WI</td>
<td align="right">0.0114308</td>
<td align="right">0.0127723</td>
<td align="right">0.0117882</td>
<td align="right">0.0081656</td>
</tr>
<tr class="odd">
<td align="left">WY</td>
<td align="right">0.0124534</td>
<td align="right">0.0215528</td>
<td align="right">0.0047059</td>
<td align="right">0.0213523</td>
</tr>
</tbody>
</table>
<p>Looking back to the table of death rate in each state, I find that Texas has a ridiculous result in death rate of white(0.7144365) death rate of black(0.3355429) and death rate of asian (0.9624866), which is abnormally high. So I think that there must be some problems in this data and hence I delete the data of Texas when I draw the map.</p>
<pre class="r code-r"><code>latest &lt;- merge(
  x     = latest,
  y     = state_map,
  by  = &quot;State&quot;,
  all.x = TRUE,
  all.y = FALSE
)</code></pre>
</div>
<div id="death-rate-map" class="section level2">
<h2>Death rate map</h2>
<div id="total-death-rate-including-tx" class="section level3">
<h3>Total death rate (including TX)</h3>
<pre class="r code-r"><code>pal = colorNumeric(c(&#39;green&#39;,&#39;red&#39;), domain=latest$DR_total)
leaflet() %&gt;% 
  addProviderTiles(&#39;CartoDB.Positron&#39;) %&gt;% 
  addCircles(
    data = latest,
    lat = ~Latitude, lng = ~Longitude, 
    opacity = 1, fillOpacity = 1, radius = 400, color = ~pal(latest$DR_total)
    ) </code></pre>
<div id="htmlwidget-e1a78b7e5636c417f191" style="width:700px;height:415.296px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-e1a78b7e5636c417f191">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["CartoDB.Positron",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircles","args":[[61.3025006,32.6010112,34.7519275,34.1682185,37.2718745,38.9979339,41.5187835,38.8993487,39.145251,32.6781248,20.46,41.9383166,45.4945756,39.739318,39.7662195,38.4987789,37.8222935,30.9733766,42.0629398,38.8063524,45.2185133,44.9435598,46.4418595,38.3046615,32.5851062,46.6797995,35.2145629,41.5008195,44.0012306,40.1430058,34.1662325,38.502032,40.1903624,35.3097654,44.1419049,40.9945928,41.5827282,33.62505,44.2126995,35.830521,31.1693363,39.4997605,38.0033855,43.8717545,38.8993487,44.7862968,43.000325],[-158.7750198,-86.6807365,-92.1313784,-111.930907,-119.2704153,-105.550567,-72.757507,-77.0145666,-75.4189206,-83.2229757,-157.505,-93.389798,-114.1424303,-89.504139,-86.441277,-98.3200779,-85.7682399,-91.4299097,-71.718067,-77.2684162,-69.0148656,-86.4158049,-93.3655146,-92.437099,-89.8772196,-110.044783,-79.8912675,-99.680902,-71.5799231,-74.7311156,-106.0260685,-117.0230604,-82.6692525,-98.7165585,-120.5380993,-77.6046984,-71.5064508,-80.9470381,-100.2471641,-85.9785989,-100.0768425,-111.547028,-79.4587861,-72.4477828,-77.0145665,-89.8267049,-107.5545669],400,null,null,{"interactive":true,"className":"","stroke":true,"color":["#00FF00","#DB9000","#C4B000","#D89500","#BEB700","#B0C400","#F84400","#F06200","#C6AE00","#CBA800","#C1B400","#C4B100","#95D800","#D59A00","#D59B00","#C3B100","#9ED200","#E67C00","#FB3500","#DC8E00","#BDB800","#F25C00","#ADC700","#C8AC00","#E77800","#B0C500","#ACC800","#90DC00","#BDB800","#FF0000","#DB9000","#C8AC00","#CFA300","#92DB00","#B7BE00","#F35800","#D99400","#C6AE00","#C6AE00","#B8BD00","#C5AF00","#15FE00","#C4B000","#AACA00","#B7BE00","#9BD500","#A5CD00"],"weight":5,"opacity":1,"fill":true,"fillColor":["#00FF00","#DB9000","#C4B000","#D89500","#BEB700","#B0C400","#F84400","#F06200","#C6AE00","#CBA800","#C1B400","#C4B100","#95D800","#D59A00","#D59B00","#C3B100","#9ED200","#E67C00","#FB3500","#DC8E00","#BDB800","#F25C00","#ADC700","#C8AC00","#E77800","#B0C500","#ACC800","#90DC00","#BDB800","#FF0000","#DB9000","#C8AC00","#CFA300","#92DB00","#B7BE00","#F35800","#D99400","#C6AE00","#C6AE00","#B8BD00","#C5AF00","#15FE00","#C4B000","#AACA00","#B7BE00","#9BD500","#A5CD00"],"fillOpacity":1},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null,null]}],"limits":{"lat":[20.46,61.3025006],"lng":[-158.7750198,-69.0148656]}},"evals":[],"jsHooks":[]}</script>
<pre class="r code-r"><code>latest &lt;- latest[!State==&quot;TX&quot;]</code></pre>
</div>
<div id="death-rate-of-white" class="section level3">
<h3>Death rate of white</h3>
<pre class="r code-r"><code>pal = colorNumeric(c(&#39;green&#39;,&#39;red&#39;), domain=latest$DR_white)
leaflet() %&gt;% 
  addProviderTiles(&#39;CartoDB.Positron&#39;) %&gt;% 
  addCircles(
    data = latest,
    lat = ~Latitude, lng = ~Longitude, 
    opacity = 1, fillOpacity = 1, radius = 400, color = ~pal(latest$DR_white)
    ) </code></pre>
<div id="htmlwidget-de6c2f8eb7dbe3ce3dec" style="width:700px;height:415.296px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-de6c2f8eb7dbe3ce3dec">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["CartoDB.Positron",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircles","args":[[61.3025006,32.6010112,34.7519275,34.1682185,37.2718745,38.9979339,41.5187835,38.8993487,39.145251,32.6781248,20.46,41.9383166,45.4945756,39.739318,39.7662195,38.4987789,37.8222935,30.9733766,42.0629398,38.8063524,45.2185133,44.9435598,46.4418595,38.3046615,32.5851062,46.6797995,35.2145629,41.5008195,44.0012306,40.1430058,34.1662325,38.502032,40.1903624,35.3097654,44.1419049,40.9945928,41.5827282,33.62505,44.2126995,35.830521,39.4997605,38.0033855,43.8717545,38.8993487,44.7862968,43.000325],[-158.7750198,-86.6807365,-92.1313784,-111.930907,-119.2704153,-105.550567,-72.757507,-77.0145666,-75.4189206,-83.2229757,-157.505,-93.389798,-114.1424303,-89.504139,-86.441277,-98.3200779,-85.7682399,-91.4299097,-71.718067,-77.2684162,-69.0148656,-86.4158049,-93.3655146,-92.437099,-89.8772196,-110.044783,-79.8912675,-99.680902,-71.5799231,-74.7311156,-106.0260685,-117.0230604,-82.6692525,-98.7165585,-120.5380993,-77.6046984,-71.5064508,-80.9470381,-100.2471641,-85.9785989,-111.547028,-79.4587861,-72.4477828,-77.0145665,-89.8267049,-107.5545669],400,null,null,{"interactive":true,"className":"","stroke":true,"color":["#32FB00","#BABB00","#98D700","#B0C500","#BDB800","#9DD300","#FF0000","#58F300","#A9CA00","#B6BF00","#62F000","#AEC600","#8DDE00","#AFC500","#98D700","#8DDD00","#77E800","#B1C400","#F25B00","#BDB800","#87E100","#BBBA00","#87E100","#9AD600","#AFC500","#75E900","#85E200","#72EB00","#B6BF00","#E77A00","#C7AD00","#ACC800","#AFC500","#74EA00","#98D700","#D69800","#BEB700","#97D700","#8DDD00","#8EDD00","#00FF00","#ADC700","#7BE600","#CFA300","#70EB00","#9ED200"],"weight":5,"opacity":1,"fill":true,"fillColor":["#32FB00","#BABB00","#98D700","#B0C500","#BDB800","#9DD300","#FF0000","#58F300","#A9CA00","#B6BF00","#62F000","#AEC600","#8DDE00","#AFC500","#98D700","#8DDD00","#77E800","#B1C400","#F25B00","#BDB800","#87E100","#BBBA00","#87E100","#9AD600","#AFC500","#75E900","#85E200","#72EB00","#B6BF00","#E77A00","#C7AD00","#ACC800","#AFC500","#74EA00","#98D700","#D69800","#BEB700","#97D700","#8DDD00","#8EDD00","#00FF00","#ADC700","#7BE600","#CFA300","#70EB00","#9ED200"],"fillOpacity":1},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null,null]}],"limits":{"lat":[20.46,61.3025006],"lng":[-158.7750198,-69.0148656]}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="death-rate-of-black" class="section level3">
<h3>Death rate of black</h3>
<pre class="r code-r"><code>pal = colorNumeric(c(&#39;green&#39;,&#39;red&#39;), domain=latest$DR_black)
leaflet() %&gt;% 
  addProviderTiles(&#39;CartoDB.Positron&#39;) %&gt;% 
  addCircles(
    data = latest,
    lat = ~Latitude, lng = ~Longitude, 
    opacity = 1, fillOpacity = 1, radius = 400, color = ~pal(latest$DR_black)
    ) </code></pre>
<div id="htmlwidget-a92715a237dd1892d622" style="width:700px;height:415.296px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-a92715a237dd1892d622">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["CartoDB.Positron",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircles","args":[[61.3025006,32.6010112,34.7519275,34.1682185,37.2718745,38.9979339,41.5187835,38.8993487,39.145251,32.6781248,20.46,41.9383166,45.4945756,39.739318,39.7662195,38.4987789,37.8222935,30.9733766,42.0629398,38.8063524,45.2185133,44.9435598,46.4418595,38.3046615,32.5851062,46.6797995,35.2145629,41.5008195,44.0012306,40.1430058,34.1662325,38.502032,40.1903624,35.3097654,44.1419049,40.9945928,41.5827282,33.62505,44.2126995,35.830521,39.4997605,38.0033855,43.8717545,38.8993487,44.7862968,43.000325],[-158.7750198,-86.6807365,-92.1313784,-111.930907,-119.2704153,-105.550567,-72.757507,-77.0145666,-75.4189206,-83.2229757,-157.505,-93.389798,-114.1424303,-89.504139,-86.441277,-98.3200779,-85.7682399,-91.4299097,-71.718067,-77.2684162,-69.0148656,-86.4158049,-93.3655146,-92.437099,-89.8772196,-110.044783,-79.8912675,-99.680902,-71.5799231,-74.7311156,-106.0260685,-117.0230604,-82.6692525,-98.7165585,-120.5380993,-77.6046984,-71.5064508,-80.9470381,-100.2471641,-85.9785989,-111.547028,-79.4587861,-72.4477828,-77.0145665,-89.8267049,-107.5545669],400,null,null,{"interactive":true,"className":"","stroke":true,"color":["#58F300","#C5AF00","#9AD600","#A0D100","#CDA500","#98D700","#F35A00","#E38100","#9FD200","#BEB700","#61F000","#8EDD00","#73EA00","#D79700","#B2C300","#9ED200","#91DB00","#C7AD00","#CFA200","#BEB700","#44F800","#F74600","#6DED00","#C1B400","#C7AD00","#00FF00","#A6CD00","#83E300","#8BDE00","#FF0000","#B1C400","#B1C400","#B2C200","#86E100","#88E000","#DB9000","#8FDC00","#B7BE00","#22FD00","#ACC800","#36FB00","#B8BD00","#2FFC00","#96D800","#86E100","#48F700"],"weight":5,"opacity":1,"fill":true,"fillColor":["#58F300","#C5AF00","#9AD600","#A0D100","#CDA500","#98D700","#F35A00","#E38100","#9FD200","#BEB700","#61F000","#8EDD00","#73EA00","#D79700","#B2C300","#9ED200","#91DB00","#C7AD00","#CFA200","#BEB700","#44F800","#F74600","#6DED00","#C1B400","#C7AD00","#00FF00","#A6CD00","#83E300","#8BDE00","#FF0000","#B1C400","#B1C400","#B2C200","#86E100","#88E000","#DB9000","#8FDC00","#B7BE00","#22FD00","#ACC800","#36FB00","#B8BD00","#2FFC00","#96D800","#86E100","#48F700"],"fillOpacity":1},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null,null]}],"limits":{"lat":[20.46,61.3025006],"lng":[-158.7750198,-69.0148656]}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="death-rate-of-asian" class="section level3">
<h3>Death rate of asian</h3>
<pre class="r code-r"><code>pal = colorNumeric(c(&#39;green&#39;,&#39;red&#39;), domain=latest$DR_asian)
leaflet() %&gt;% 
  addProviderTiles(&#39;CartoDB.Positron&#39;) %&gt;% 
  addCircles(
    data = latest,
    lat = ~Latitude, lng = ~Longitude, 
    opacity = 1, fillOpacity = 1, radius = 400, color = ~pal(latest$DR_asian)
    ) </code></pre>
<div id="htmlwidget-49d0d6403862c9ba4bae" style="width:700px;height:415.296px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-49d0d6403862c9ba4bae">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["CartoDB.Positron",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircles","args":[[61.3025006,32.6010112,34.7519275,34.1682185,37.2718745,38.9979339,41.5187835,38.8993487,39.145251,32.6781248,20.46,41.9383166,45.4945756,39.739318,39.7662195,38.4987789,37.8222935,30.9733766,42.0629398,38.8063524,45.2185133,44.9435598,46.4418595,38.3046615,32.5851062,46.6797995,35.2145629,41.5008195,44.0012306,40.1430058,34.1662325,38.502032,40.1903624,35.3097654,44.1419049,40.9945928,41.5827282,33.62505,44.2126995,35.830521,39.4997605,38.0033855,43.8717545,38.8993487,44.7862968,43.000325],[-158.7750198,-86.6807365,-92.1313784,-111.930907,-119.2704153,-105.550567,-72.757507,-77.0145666,-75.4189206,-83.2229757,-157.505,-93.389798,-114.1424303,-89.504139,-86.441277,-98.3200779,-85.7682399,-91.4299097,-71.718067,-77.2684162,-69.0148656,-86.4158049,-93.3655146,-92.437099,-89.8772196,-110.044783,-79.8912675,-99.680902,-71.5799231,-74.7311156,-106.0260685,-117.0230604,-82.6692525,-98.7165585,-120.5380993,-77.6046984,-71.5064508,-80.9470381,-100.2471641,-85.9785989,-111.547028,-79.4587861,-72.4477828,-77.0145665,-89.8267049,-107.5545669],400,null,null,{"interactive":true,"className":"","stroke":true,"color":["#95D900","#8BDE00","#99D600","#BBBA00","#ED6A00","#B8BD00","#DE8B00","#ABC900","#5CF200","#B2C300","#FF0000","#B8BD00","#A3CF00","#DD8D00","#72EA00","#93DA00","#60F100","#43F800","#D89500","#E97400","#5CF200","#B5C000","#97D800","#ACC800","#9BD500","#00FF00","#7CE600","#8CDE00","#93DA00","#FC2C00","#AEC600","#D49C00","#89DF00","#6CED00","#96D800","#D0A200","#ADC700","#8ADF00","#8EDD00","#84E200","#78E800","#B3C200","#66EF00","#E77900","#76E900","#C8AC00"],"weight":5,"opacity":1,"fill":true,"fillColor":["#95D900","#8BDE00","#99D600","#BBBA00","#ED6A00","#B8BD00","#DE8B00","#ABC900","#5CF200","#B2C300","#FF0000","#B8BD00","#A3CF00","#DD8D00","#72EA00","#93DA00","#60F100","#43F800","#D89500","#E97400","#5CF200","#B5C000","#97D800","#ACC800","#9BD500","#00FF00","#7CE600","#8CDE00","#93DA00","#FC2C00","#AEC600","#D49C00","#89DF00","#6CED00","#96D800","#D0A200","#ADC700","#8ADF00","#8EDD00","#84E200","#78E800","#B3C200","#66EF00","#E77900","#76E900","#C8AC00"],"fillOpacity":1},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null,null]}],"limits":{"lat":[20.46,61.3025006],"lng":[-158.7750198,-69.0148656]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>Just from these data, I think there is no clear association between races and death rate of COVID-19. Both in CA and country level, the death rate of all three races approach to the same level finally. And for top5 states with highest death rate in each race, TX is top1 of all three races and MA, NJ, CT, PA, MI also appear more than one time. Hence, in my opinion, the death rate is highly depend on the action of the State rather than races, for example, the burden of medical system, the policy to restrict COVID-19 etc. Although the number of states with DR_white to be the highest DR among three races is greatest (30), the difference among average DR is not that so great. This probably is caused by samples collection. The majority of United States population is white, hence the data collected in white might be greater, leading to a relatively higher DR. I saw a lot of data showed a different result from these data, which indicated that death rate of black is highest among all races. That might be caused by inequality of medical distribution at the stage of onset of COVID-19. As the burden of medical resource relieved and government took action to restrict COVID-19 and gave supports to citizens, I believe that death rate that approaches to the same level is a right trend.</p>
<p><br> <br></p>
</div>

<p>Copyright &copy; 2021, Nicky Nie.</p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
